### ISSUE TITLE
Unclear On Instructions

### ISSUE THREAD

**Issue by Xarcell** [danpros/htmly-twentyfifteen#1]
I uploaded the theme to the themes directory and renamed. It says: "Change the  views.root  using /admin/config to  themes/twentyfifteen". There is no /admin/config directory. What I did was changed view.root in config/config.ini . However, it only shows that theme only when I'm logged in though.

**Comment by danpros** [comment]
I mean go to http://example.com/admin/config :smile:

**Comment by danpros** [comment]
Close this one.
